name: CI
on: [push]
jobs:
  functionality-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the codebase
      uses: actions/checkout@v1
    - name: Run composer install
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
    - name: Run PHPUnit Tests
      run: vendor/bin/phpunit